site_name: Modern Graphics Engine Guide
copyright: Copyright &copy; 2016 - 2023 Italink
docs_dir: Docs
repo_url: https://github.com/Italink/ModernGraphicsEngineGuide
repo_name: Github
nav:
    - '开篇' : 'README.md'
    - C++:
        - '0 - 计算机发展史': '00-C++/1.计算机发展史.md'
        - '1 - C++基础': '00-C++/2.C++基础.md'
        - '2 - 工具链': '00-C++/3.工具链.md'
        - '3 - 宏、模板、反射': '00-C++/4.宏、模板、反射.md'
        - '4 - 内存管理': '00-C++/5.内存管理.md'
        - '5 - GUI': '00-C++/6.GUI.md'
    - '图形API':
        - "0 - 概述" : "01-GraphicsAPI/0.概述.md"
        - "1 - 基础" : "01-GraphicsAPI/1.基础.md"
        - "2 - 图形渲染管线" : "01-GraphicsAPI/2.图形渲染管线.md"
        - "3 - 着色器" : "01-GraphicsAPI/3.着色器.md"
        - "4 - 缓冲区与纹理" : "01-GraphicsAPI/4.缓冲区与纹理.md"
        - "5 - 3D空间" : "01-GraphicsAPI/5.三维空间.md"
        - "6 - 图形API进阶" : "01-GraphicsAPI/6.图形渲染进阶.md"
    - '引擎技术':
        - "0 - 渲染架构" : "02-EngineTechnology/0.渲染架构.md"
        - "1 - 编辑器架构" : "02-EngineTechnology/1.编辑器架构.md"
        - "2 - DebugDraw" : "02-EngineTechnology/Waitting.md"
        - "3 - GPU调试" : "02-EngineTechnology/Waitting.md"
    # - '图形技术':
    #     - '0 - 网格体渲染': "03-GraphicsTechnology/Waitting.md"
    #     - '1 - 天空盒':  "03-GraphicsTechnology/Waitting.md"
    #     - '2 - GPU粒子':  "03-GraphicsTechnology/Waitting.md"
    #     - '3 - 后期滤镜':  "03-GraphicsTechnology/Waitting.md"
    #     - '4 - 光照':  "03-GraphicsTechnology/Waitting.md"
    #     - '5 - 体积雾':  "03-GraphicsTechnology/Waitting.md"
    #     - '6 - 天空大气':  "03-GraphicsTechnology/Waitting.md"
    #     - '7 - 地形':  "03-GraphicsTechnology/Waitting.md"
    - 'Unreal Engine':
        - '0 - 基础编程': '04-UnrealEngine/0.基础编程.md'
        - '1 - Slate 开发': '04-UnrealEngine/1.Slate开发.md'
        - '2 - 插件开发': '04-UnrealEngine/2.插件开发.md'
        - '3 - 粒子系统': '04-UnrealEngine/3.粒子系统.md'
        - '4 - Niagara 性能优化': '04-UnrealEngine/4.Niagra性能优化.md'
        - '5 - Fluid Ninja 流体插件': '04-UnrealEngine/5.FluidNinja流体插件.md'
        - '6 - 开放世界制作': '04-UnrealEngine/6.开放世界制作.md'
        - '7 - 音频开发': '04-UnrealEngine/7.音频开发.md'
        - '9 - 植被优化': '04-UnrealEngine/9.开放世界中的植被优化技术.md'
        - '10 - LOD不完全指南': '04-UnrealEngine/10.LOD不完全指南.md'
        - '12 - 程序化内容管理': '04-UnrealEngine/12.程序化内容管理.md'
        - '16 - 3DGaussianSplatting': '04-UnrealEngine/16.3DGaussianSplatting.md'
    - "开源":
        - 'UnrealEngine':
            - 'Gaussian Splatting': '05-OpenSource/UnrealEngine/GaussianSplattingForUnrealEngine.md'
        - 'C++':
            - 'C++反射编译器': '05-OpenSource/C++/C++反射编译器.md'
        - 'Qt':
            - '音频可视化软件-Specinker(已闭源)': '05-OpenSource/Qt/音频可视化软件-Specinker.md'
            - '频谱分析器': '05-OpenSource/Qt/频谱分析器.md'
            - 'Qt拟态窗口滤镜': '05-OpenSource/Qt/Qt拟态窗口滤镜.md'
            - 'Qt屏幕取色器': '05-OpenSource/Qt/Qt屏幕取色器.md'
            - 'Qt渐变调色器': '05-OpenSource/Qt/Qt渐变调色器.md'
            - 'Qt桌面粒子特效': '05-OpenSource/Qt/Qt桌面粒子特效.md'
            - 'Qt桌面水面波纹特效': '05-OpenSource/Qt/Qt桌面水面波纹特效.md'
    - '个人博客':
        - 06-Blog/index.md
    
theme:
    icon:
        repo: fontawesome/brands/github
    language: zh
    name: material
    custom_dir: Docs/Stylesheet
    features:
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - announce.dismiss
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
plugins:
    - glightbox
    - search:
        separator: '[\s\u200b\-]'
    - git-revision-date-localized:
        enable_creation_date: true
        type: iso_datetime
    - git-committers:
        repository: Italink/ModernGraphicsEngineGuide
        branch: main
        docs_path: Docs
        enabled: true
        token: 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
    - blog:
        blog_dir: 06-Blog
        post_dir: "{blog}/Posts"
        blog_toc: true
        archive_date_format: MMMM yyyy
        archive_url_date_format: yyyy/MM
        archive_toc: true
extra:
  analytics:
    provider: google
    property: G-S1J8MN27P8
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Italink
    - icon: simple/zhihu
      link: https://www.zhihu.com/people/italink
  copyright: Copyright &copy; 2016 - 2020 Martin Donath
markdown_extensions:
    - abbr
    - admonition
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
extra_css:
  - Stylesheet/mkdocs_extra.css

