#ifndef QENGINECOREPLUGIN_API_H
#define QENGINECOREPLUGIN_API_H

#include <QtCore/qglobal.h>

#if defined(QENGINECOREPLUGIN_LIBRARY)
#  define QENGINECOREPLUGIN_API Q_DECL_EXPORT
#else
#  define QENGINECOREPLUGIN_API Q_DECL_IMPORT
#endif

#endif // QENGINECOREPLUGIN_API_H