#ifndef DETAILCUSTOMIZATION_API_H
#define DETAILCUSTOMIZATION_API_H

#include <QtCore/qglobal.h>

#if defined(DETAILCUSTOMIZATION_LIBRARY)
#  define DETAILCUSTOMIZATION_API Q_DECL_EXPORT
#else
#  define DETAILCUSTOMIZATION_API Q_DECL_IMPORT
#endif

#endif // DETAILCUSTOMIZATION_API_H